name: NodeJS CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout node version
              uses: actions/checkout@v2
            - name: Setup NodeJS
              uses: actions/setup-node@v2
              with:
                  node-version: '22'
            - name: Install dependencies 
              run: npm install
            - name: test nodejs
              run: npm run check